services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: elasticsearch
    platform: linux/amd64
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS: -Xms256m -Xmx256m"
      - "http.cors.enabled=true"
    ports:
      - "9200:9200"
    volumes:
      - ./logging/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  logstash:
    image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
    container_name: logstash
    platform: linux/amd64
    volumes:
      - ./logging/:/logging/
      - ./logging/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logging/logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
    environment:
      - "ES_JAVA_OPTS: -Xms256m -Xmx256m"
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: kibana
    platform: linux/amd64
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:${STACK_VERSION}
    container_name: filebeat
    platform: linux/amd64
    volumes:
      - ./logging/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./Moitda-Backend/logs:/var/log/spring-boot
    depends_on:
      - logstash
      - elasticsearch
      - kibana
    command: filebeat -e -c /usr/share/filebeat/filebeat.yml